### ISSUE TITLE
Fails to correctly merge bes and lu

### ISSUE THREAD

**Issue by phil20686** [chrishanretty/euref_priors#2]
Hi 

I was trying to replicate your work but the code in the git doesnt appear to work, I have traced the issue to the fact that when i download BES2015_w6_v1.2.sav and load it the "profile_oslaua" column is integers, where as in the data/bes_to_gss_lu it is free text names, this means that the two lines:

`bes <- merge(bes, lu, all.x = T, all.y = F)
bes <- subset(bes, !is.na(GSSCode))`

end up trimming all of the data out of bes, since there are zero matches on the merge resulting in the GSSCode column being entirely NA, and thus bes has zero rows.

Is it possible that when you wrote this you were not using the direct download but had somehow already edited it?

(PS: ncidentally, wouldn't setting all.x=False drop all rows with no match in profile_oslaua and hence all GSSCode == na anyway, without the need for the subset command?)

**Comment by chrishanretty** [comment]
When I load the BES file, "profile_oslaua" is a factor, and merges okay. It sounds like the BES file isn't loading properly for you. You may want to check your version of the rio package (I used 0.3.0) and its dependencies.

**Comment by phil20686** [comment]
Yeah, I had version 4.8, replaced it with library(foreign) and bes = read.spss("data/BES2015_W6_v1.2.sav", to.data.frame = TRUE)

and that seems to work.

Maybe note in the comments that your version is far from current... :)

Thanks for getting back to me quickly.
